bind: "--bind /scratch2/:/scratch2/"
SingImage: "~/singularity-images/trRosetta.simg"
trRosettaPath: "~/git/bioinfo-toolbox/trRosetta/"
jhparams: "-N 3 --cpu 8"
workdir: "./"
dockq: "/home/arnee/git/DockQ/DockQ.py"
cns_solve: "/home/arnee/bin/cns_solve_1.3"
