bin/seqid.py seq_chains/1a0s_P.seq seq_chains/1a0s_Q.seq
bin/seqid.py seq_chains/1af6_A.seq seq_chains/1af6_B.seq
bin/seqid.py seq_chains/1aig_L.seq seq_chains/1aig_M.seq
bin/seqid.py seq_chains/1ay2_A.seq seq_chains/1ay2_B.seq
bin/seqid.py seq_chains/1bcc_D.seq seq_chains/1bcc_E.seq
bin/seqid.py seq_chains/1be3_C.seq seq_chains/1be3_G.seq
bin/seqid.py seq_chains/1be3_E.seq seq_chains/1be3_J.seq
bin/seqid.py seq_chains/1bh3_A.seq seq_chains/1bh3_B.seq
bin/seqid.py seq_chains/1c17_L.seq seq_chains/1c17_M.seq
bin/seqid.py seq_chains/1dxr_H.seq seq_chains/1dxr_M.seq
bin/seqid.py seq_chains/1dxr_L.seq seq_chains/1dxr_M.seq
bin/seqid.py seq_chains/1e7p_C.seq seq_chains/1e7p_F.seq
bin/seqid.py seq_chains/1ehk_A.seq seq_chains/1ehk_B.seq
bin/seqid.py seq_chains/1ezv_C.seq seq_chains/1ezv_H.seq
bin/seqid.py seq_chains/1fft_A.seq seq_chains/1fft_B.seq
bin/seqid.py seq_chains/1fft_A.seq seq_chains/1fft_C.seq
bin/seqid.py seq_chains/1fx8_A.seq seq_chains/1fx8_C.seq
bin/seqid.py seq_chains/1hgv_A.seq seq_chains/1hgv_G.seq
bin/seqid.py seq_chains/1ifl_A.seq seq_chains/1ifl_F.seq
bin/seqid.py seq_chains/1ifm_A.seq seq_chains/1ifm_F.seq
bin/seqid.py seq_chains/1ifp_A.seq seq_chains/1ifp_G.seq
bin/seqid.py seq_chains/1kf6_C.seq seq_chains/1kf6_D.seq
bin/seqid.py seq_chains/1kpl_A.seq seq_chains/1kpl_B.seq
bin/seqid.py seq_chains/1kqf_B.seq seq_chains/1kqf_C.seq
bin/seqid.py seq_chains/1l7v_A.seq seq_chains/1l7v_B.seq
bin/seqid.py seq_chains/1lgh_A.seq seq_chains/1lgh_D.seq
bin/seqid.py seq_chains/1m56_A.seq seq_chains/1m56_B.seq
bin/seqid.py seq_chains/1mhs_A.seq seq_chains/1mhs_B.seq
bin/seqid.py seq_chains/1nek_C.seq seq_chains/1nek_D.seq
bin/seqid.py seq_chains/1nek_D.seq seq_chains/1nek_H.seq
bin/seqid.py seq_chains/1nkz_A.seq seq_chains/1nkz_C.seq
bin/seqid.py seq_chains/1occ_A.seq seq_chains/1occ_B.seq
bin/seqid.py seq_chains/1occ_A.seq seq_chains/1occ_C.seq
bin/seqid.py seq_chains/1occ_A.seq seq_chains/1occ_D.seq
bin/seqid.py seq_chains/1occ_A.seq seq_chains/1occ_L.seq
bin/seqid.py seq_chains/1occ_A.seq seq_chains/1occ_M.seq
bin/seqid.py seq_chains/1occ_B.seq seq_chains/1occ_I.seq
bin/seqid.py seq_chains/1occ_C.seq seq_chains/1occ_G.seq
bin/seqid.py seq_chains/1occ_D.seq seq_chains/1occ_K.seq
bin/seqid.py seq_chains/1occ_D.seq seq_chains/1occ_M.seq
bin/seqid.py seq_chains/1occ_L.seq seq_chains/1occ_M.seq
bin/seqid.py seq_chains/1ocr_C.seq seq_chains/1ocr_J.seq
bin/seqid.py seq_chains/1orq_C.seq seq_chains/1orq_D.seq
bin/seqid.py seq_chains/1q90_A.seq seq_chains/1q90_D.seq
bin/seqid.py seq_chains/1q90_A.seq seq_chains/1q90_N.seq
bin/seqid.py seq_chains/1q90_D.seq seq_chains/1q90_N.seq
bin/seqid.py seq_chains/1qle_A.seq seq_chains/1qle_C.seq
bin/seqid.py seq_chains/1rh5_A.seq seq_chains/1rh5_C.seq
bin/seqid.py seq_chains/1rhz_A.seq seq_chains/1rhz_B.seq
bin/seqid.py seq_chains/1s5l_A.seq seq_chains/1s5l_I.seq
bin/seqid.py seq_chains/1sqq_J.seq seq_chains/1sqq_K.seq
bin/seqid.py seq_chains/1uun_A.seq seq_chains/1uun_B.seq
bin/seqid.py seq_chains/1vf5_E.seq seq_chains/1vf5_F.seq
bin/seqid.py seq_chains/1w5c_A.seq seq_chains/1w5c_D.seq
bin/seqid.py seq_chains/1xl6_A.seq seq_chains/1xl6_B.seq
bin/seqid.py seq_chains/1xme_A.seq seq_chains/1xme_B.seq
bin/seqid.py seq_chains/1yc9_A.seq seq_chains/1yc9_B.seq
bin/seqid.py seq_chains/1yst_H.seq seq_chains/1yst_M.seq
bin/seqid.py seq_chains/2axt_C.seq seq_chains/2axt_Z.seq
bin/seqid.py seq_chains/2axt_E.seq seq_chains/2axt_F.seq
bin/seqid.py seq_chains/2b6p_A.seq seq_chains/2b6p_B.seq
bin/seqid.py seq_chains/2bg9_A.seq seq_chains/2bg9_B.seq
bin/seqid.py seq_chains/2bg9_A.seq seq_chains/2bg9_E.seq
bin/seqid.py seq_chains/2bg9_D.seq seq_chains/2bg9_E.seq
bin/seqid.py seq_chains/2bhw_A.seq seq_chains/2bhw_B.seq
bin/seqid.py seq_chains/2bl2_A.seq seq_chains/2bl2_B.seq
bin/seqid.py seq_chains/2e74_A.seq seq_chains/2e74_B.seq
bin/seqid.py seq_chains/2e74_A.seq seq_chains/2e74_G.seq
bin/seqid.py seq_chains/2e74_B.seq seq_chains/2e74_C.seq
bin/seqid.py seq_chains/2evu_A.seq seq_chains/2evu_C.seq
bin/seqid.py seq_chains/2f95_A.seq seq_chains/2f95_B.seq
bin/seqid.py seq_chains/2f95_B.seq seq_chains/2f95_D.seq
bin/seqid.py seq_chains/2fbw_C.seq seq_chains/2fbw_D.seq
bin/seqid.py seq_chains/2fgr_A.seq seq_chains/2fgr_B.seq
bin/seqid.py seq_chains/2fyn_A.seq seq_chains/2fyn_B.seq
bin/seqid.py seq_chains/2fyn_A.seq seq_chains/2fyn_D.seq
bin/seqid.py seq_chains/2fyn_B.seq seq_chains/2fyn_C.seq
bin/seqid.py seq_chains/2gsk_A.seq seq_chains/2gsk_B.seq
bin/seqid.py seq_chains/2h8a_A.seq seq_chains/2h8a_B.seq
bin/seqid.py seq_chains/2hyd_A.seq seq_chains/2hyd_B.seq
bin/seqid.py seq_chains/2ifo_A.seq seq_chains/2ifo_G.seq
bin/seqid.py seq_chains/2iqr_A.seq seq_chains/2iqr_C.seq
bin/seqid.py seq_chains/2iqv_A.seq seq_chains/2iqv_C.seq
bin/seqid.py seq_chains/2ixx_A.seq seq_chains/2ixx_B.seq
bin/seqid.py seq_chains/2j58_A.seq seq_chains/2j58_B.seq
bin/seqid.py seq_chains/2kdc_A.seq seq_chains/2kdc_B.seq
bin/seqid.py seq_chains/2kix_A.seq seq_chains/2kix_B.seq
bin/seqid.py seq_chains/2knc_A.seq seq_chains/2knc_B.seq
bin/seqid.py seq_chains/2l2t_A.seq seq_chains/2l2t_B.seq
bin/seqid.py seq_chains/2l35_A.seq seq_chains/2l35_B.seq
bin/seqid.py seq_chains/2lme_A.seq seq_chains/2lme_B.seq
bin/seqid.py seq_chains/2lzl_A.seq seq_chains/2lzl_B.seq
bin/seqid.py seq_chains/2m20_A.seq seq_chains/2m20_B.seq
bin/seqid.py seq_chains/2m3g_A.seq seq_chains/2m3g_B.seq
bin/seqid.py seq_chains/2met_A.seq seq_chains/2met_B.seq
bin/seqid.py seq_chains/2mjo_A.seq seq_chains/2mjo_B.seq
bin/seqid.py seq_chains/2mpn_A.seq seq_chains/2mpn_B.seq
bin/seqid.py seq_chains/2n70_A.seq seq_chains/2n70_B.seq
bin/seqid.py seq_chains/2nq2_A.seq seq_chains/2nq2_B.seq
bin/seqid.py seq_chains/2nuu_A.seq seq_chains/2nuu_B.seq
bin/seqid.py seq_chains/2o01_H.seq seq_chains/2o01_L.seq
bin/seqid.py seq_chains/2o9g_A.seq seq_chains/2o9g_C.seq
bin/seqid.py seq_chains/2oar_A.seq seq_chains/2oar_B.seq
bin/seqid.py seq_chains/2onk_C.seq seq_chains/2onk_D.seq
bin/seqid.py seq_chains/2por_A.seq seq_chains/2por_B.seq
bin/seqid.py seq_chains/2q7m_A.seq seq_chains/2q7m_C.seq
bin/seqid.py seq_chains/2qi9_A.seq seq_chains/2qi9_F.seq
bin/seqid.py seq_chains/2qts_A.seq seq_chains/2qts_B.seq
bin/seqid.py seq_chains/2uui_A.seq seq_chains/2uui_B.seq
bin/seqid.py seq_chains/2vpw_C.seq seq_chains/2vpw_G.seq
bin/seqid.py seq_chains/2vr0_C.seq seq_chains/2vr0_F.seq
bin/seqid.py seq_chains/2w1p_A.seq seq_chains/2w1p_B.seq
bin/seqid.py seq_chains/2wcd_A.seq seq_chains/2wcd_B.seq
bin/seqid.py seq_chains/2wll_A.seq seq_chains/2wll_D.seq
bin/seqid.py seq_chains/2wpd_J.seq seq_chains/2wpd_K.seq
bin/seqid.py seq_chains/2wsw_A.seq seq_chains/2wsw_B.seq
bin/seqid.py seq_chains/2ww9_A.seq seq_chains/2ww9_B.seq
bin/seqid.py seq_chains/2wwb_A.seq seq_chains/2wwb_B.seq
bin/seqid.py seq_chains/2wwb_A.seq seq_chains/2wwb_C.seq
bin/seqid.py seq_chains/2x2v_A.seq seq_chains/2x2v_B.seq
bin/seqid.py seq_chains/2xq2_A.seq seq_chains/2xq2_B.seq
bin/seqid.py seq_chains/2xqt_A.seq seq_chains/2xqt_B.seq
bin/seqid.py seq_chains/2yev_A.seq seq_chains/2yev_B.seq
bin/seqid.py seq_chains/2yev_A.seq seq_chains/2yev_C.seq
bin/seqid.py seq_chains/2yew_B.seq seq_chains/2yew_C.seq
bin/seqid.py seq_chains/2yn9_A.seq seq_chains/2yn9_B.seq
bin/seqid.py seq_chains/2yvx_A.seq seq_chains/2yvx_B.seq
bin/seqid.py seq_chains/2zw3_A.seq seq_chains/2zw3_B.seq
bin/seqid.py seq_chains/3a2s_A.seq seq_chains/3a2s_D.seq
bin/seqid.py seq_chains/3anz_A.seq seq_chains/3anz_B.seq
bin/seqid.py seq_chains/3b07_A.seq seq_chains/3b07_H.seq
bin/seqid.py seq_chains/3b07_B.seq seq_chains/3b07_C.seq
bin/seqid.py seq_chains/3b5x_A.seq seq_chains/3b5x_B.seq
bin/seqid.py seq_chains/3b8e_A.seq seq_chains/3b8e_B.seq
bin/seqid.py seq_chains/3b9y_A.seq seq_chains/3b9y_E.seq
bin/seqid.py seq_chains/3bo0_A.seq seq_chains/3bo0_B.seq
bin/seqid.py seq_chains/3c02_A.seq seq_chains/3c02_C.seq
bin/seqid.py seq_chains/3cx5_C.seq seq_chains/3cx5_D.seq
bin/seqid.py seq_chains/3cx5_E.seq seq_chains/3cx5_I.seq
bin/seqid.py seq_chains/3din_C.seq seq_chains/3din_D.seq
bin/seqid.py seq_chains/3din_C.seq seq_chains/3din_E.seq
bin/seqid.py seq_chains/3eff_K.seq seq_chains/3eff_L.seq
bin/seqid.py seq_chains/3egw_C.seq seq_chains/3egw_F.seq
bin/seqid.py seq_chains/3emo_A.seq seq_chains/3emo_B.seq
bin/seqid.py seq_chains/3hd6_A.seq seq_chains/3hd6_C.seq
bin/seqid.py seq_chains/3hd7_A.seq seq_chains/3hd7_B.seq
bin/seqid.py seq_chains/3j01_A.seq seq_chains/3j01_B.seq
bin/seqid.py seq_chains/3j0c_A.seq seq_chains/3j0c_B.seq
bin/seqid.py seq_chains/3j1z_P.seq seq_chains/3j1z_Q.seq
bin/seqid.py seq_chains/3j2w_E.seq seq_chains/3j2w_Q.seq
bin/seqid.py seq_chains/3j45_G.seq seq_chains/3j45_y.seq
bin/seqid.py seq_chains/3j46_n.seq seq_chains/3j46_y.seq
bin/seqid.py seq_chains/3j8h_A.seq seq_chains/3j8h_C.seq
bin/seqid.py seq_chains/3j9c_A.seq seq_chains/3j9c_B.seq
bin/seqid.py seq_chains/3j9p_A.seq seq_chains/3j9p_B.seq
bin/seqid.py seq_chains/3j9t_Q.seq seq_chains/3j9t_a.seq
bin/seqid.py seq_chains/3j9t_R.seq seq_chains/3j9t_a.seq
bin/seqid.py seq_chains/3jaf_A.seq seq_chains/3jaf_B.seq
bin/seqid.py seq_chains/3jcf_A.seq seq_chains/3jcf_B.seq
bin/seqid.py seq_chains/3jcu_I.seq seq_chains/3jcu_W.seq
bin/seqid.py seq_chains/3jcu_L.seq seq_chains/3jcu_M.seq
bin/seqid.py seq_chains/3jqo_A.seq seq_chains/3jqo_n.seq
bin/seqid.py seq_chains/3kzi_D.seq seq_chains/3kzi_F.seq
bin/seqid.py seq_chains/3lut_I.seq seq_chains/3lut_J.seq
bin/seqid.py seq_chains/3m6e_A.seq seq_chains/3m6e_B.seq
bin/seqid.py seq_chains/3m73_A.seq seq_chains/3m73_F.seq
bin/seqid.py seq_chains/3mk7_A.seq seq_chains/3mk7_B.seq
bin/seqid.py seq_chains/3mk7_A.seq seq_chains/3mk7_C.seq
bin/seqid.py seq_chains/3mp7_A.seq seq_chains/3mp7_B.seq
bin/seqid.py seq_chains/3o0r_B.seq seq_chains/3o0r_C.seq
bin/seqid.py seq_chains/3o44_A.seq seq_chains/3o44_B.seq
bin/seqid.py seq_chains/3odu_A.seq seq_chains/3odu_B.seq
bin/seqid.py seq_chains/3org_A.seq seq_chains/3org_D.seq
bin/seqid.py seq_chains/3pjz_A.seq seq_chains/3pjz_B.seq
bin/seqid.py seq_chains/3pux_F.seq seq_chains/3pux_G.seq
bin/seqid.py seq_chains/3q7k_B.seq seq_chains/3q7k_C.seq
bin/seqid.py seq_chains/3qbg_A.seq seq_chains/3qbg_B.seq
bin/seqid.py seq_chains/3qf4_A.seq seq_chains/3qf4_B.seq
bin/seqid.py seq_chains/3qnq_A.seq seq_chains/3qnq_B.seq
bin/seqid.py seq_chains/3rfz_A.seq seq_chains/3rfz_B.seq
bin/seqid.py seq_chains/3rko_A.seq seq_chains/3rko_J.seq
bin/seqid.py seq_chains/3rko_J.seq seq_chains/3rko_K.seq
bin/seqid.py seq_chains/3rko_J.seq seq_chains/3rko_L.seq
bin/seqid.py seq_chains/3rko_J.seq seq_chains/3rko_N.seq
bin/seqid.py seq_chains/3rko_K.seq seq_chains/3rko_N.seq
bin/seqid.py seq_chains/3rko_L.seq seq_chains/3rko_M.seq
bin/seqid.py seq_chains/3rko_L.seq seq_chains/3rko_N.seq
bin/seqid.py seq_chains/3rko_M.seq seq_chains/3rko_N.seq
bin/seqid.py seq_chains/3spg_A.seq seq_chains/3spg_C.seq
bin/seqid.py seq_chains/3tdo_C.seq seq_chains/3tdo_D.seq
bin/seqid.py seq_chains/3tij_A.seq seq_chains/3tij_B.seq
bin/seqid.py seq_chains/3tui_A.seq seq_chains/3tui_B.seq
bin/seqid.py seq_chains/3udc_A.seq seq_chains/3udc_B.seq
bin/seqid.py seq_chains/3ukm_A.seq seq_chains/3ukm_B.seq
bin/seqid.py seq_chains/3um7_A.seq seq_chains/3um7_B.seq
bin/seqid.py seq_chains/3ux4_A.seq seq_chains/3ux4_B.seq
bin/seqid.py seq_chains/3vou_A.seq seq_chains/3vou_B.seq
bin/seqid.py seq_chains/3vr8_C.seq seq_chains/3vr8_D.seq
bin/seqid.py seq_chains/3w5a_B.seq seq_chains/3w5a_C.seq
bin/seqid.py seq_chains/3w9t_A.seq seq_chains/3w9t_B.seq
bin/seqid.py seq_chains/3wgu_A.seq seq_chains/3wgu_B.seq
bin/seqid.py seq_chains/3wmm_7.seq seq_chains/3wmm_9.seq
bin/seqid.py seq_chains/3wu2_a.seq seq_chains/3wu2_c.seq
bin/seqid.py seq_chains/4a01_A.seq seq_chains/4a01_B.seq
bin/seqid.py seq_chains/4aip_A.seq seq_chains/4aip_B.seq
bin/seqid.py seq_chains/4au5_A.seq seq_chains/4au5_B.seq
bin/seqid.py seq_chains/4av3_A.seq seq_chains/4av3_B.seq
bin/seqid.py seq_chains/4ayx_A.seq seq_chains/4ayx_B.seq
bin/seqid.py seq_chains/4bem_A.seq seq_chains/4bem_J.seq
bin/seqid.py seq_chains/4bpm_A.seq seq_chains/4bpm_B.seq
bin/seqid.py seq_chains/4bwz_A.seq seq_chains/4bwz_B.seq
bin/seqid.py seq_chains/4c48_A.seq seq_chains/4c48_C.seq
bin/seqid.py seq_chains/4c7r_A.seq seq_chains/4c7r_B.seq
bin/seqid.py seq_chains/4chv_A.seq seq_chains/4chv_B.seq
bin/seqid.py seq_chains/4cz9_A.seq seq_chains/4cz9_B.seq
bin/seqid.py seq_chains/4czb_A.seq seq_chains/4czb_B.seq
bin/seqid.py seq_chains/4dnr_C.seq seq_chains/4dnr_F.seq
bin/seqid.py seq_chains/4dxw_A.seq seq_chains/4dxw_B.seq
bin/seqid.py seq_chains/4ev6_A.seq seq_chains/4ev6_E.seq
bin/seqid.py seq_chains/4ezc_A.seq seq_chains/4ezc_B.seq
bin/seqid.py seq_chains/4f35_A.seq seq_chains/4f35_B.seq
bin/seqid.py seq_chains/4gd3_A.seq seq_chains/4gd3_S.seq
bin/seqid.py seq_chains/4gd3_A.seq seq_chains/4gd3_T.seq
bin/seqid.py seq_chains/4gx2_A.seq seq_chains/4gx2_B.seq
bin/seqid.py seq_chains/4h56_A.seq seq_chains/4h56_B.seq
bin/seqid.py seq_chains/4he8_A.seq seq_chains/4he8_J.seq
bin/seqid.py seq_chains/4he8_A.seq seq_chains/4he8_K.seq
bin/seqid.py seq_chains/4he8_J.seq seq_chains/4he8_K.seq
bin/seqid.py seq_chains/4he8_J.seq seq_chains/4he8_N.seq
bin/seqid.py seq_chains/4he8_K.seq seq_chains/4he8_N.seq
bin/seqid.py seq_chains/4he8_L.seq seq_chains/4he8_M.seq
bin/seqid.py seq_chains/4he8_L.seq seq_chains/4he8_N.seq
bin/seqid.py seq_chains/4he8_M.seq seq_chains/4he8_N.seq
bin/seqid.py seq_chains/4hea_A.seq seq_chains/4hea_H.seq
bin/seqid.py seq_chains/4hea_A.seq seq_chains/4hea_J.seq
bin/seqid.py seq_chains/4hea_H.seq seq_chains/4hea_J.seq
bin/seqid.py seq_chains/4hg6_A.seq seq_chains/4hg6_B.seq
bin/seqid.py seq_chains/4hkr_A.seq seq_chains/4hkr_B.seq
bin/seqid.py seq_chains/4huq_S.seq seq_chains/4huq_T.seq
bin/seqid.py seq_chains/4hw9_A.seq seq_chains/4hw9_B.seq
bin/seqid.py seq_chains/4hyg_A.seq seq_chains/4hyg_B.seq
bin/seqid.py seq_chains/4hzu_S.seq seq_chains/4hzu_T.seq
bin/seqid.py seq_chains/4ire_A.seq seq_chains/4ire_B.seq
bin/seqid.py seq_chains/4j3o_D.seq seq_chains/4j3o_G.seq
bin/seqid.py seq_chains/4j3o_F.seq seq_chains/4j3o_G.seq
bin/seqid.py seq_chains/4jbw_F.seq seq_chains/4jbw_G.seq
bin/seqid.py seq_chains/4jc6_A.seq seq_chains/4jc6_C.seq
bin/seqid.py seq_chains/4k0e_A.seq seq_chains/4k0e_C.seq
bin/seqid.py seq_chains/4kjs_A.seq seq_chains/4kjs_B.seq
bin/seqid.py seq_chains/4knf_B.seq seq_chains/4knf_C.seq
bin/seqid.py seq_chains/4l35_A.seq seq_chains/4l35_B.seq
bin/seqid.py seq_chains/4l6v_A.seq seq_chains/4l6v_K.seq
bin/seqid.py seq_chains/4mnd_A.seq seq_chains/4mnd_B.seq
bin/seqid.py seq_chains/4mt4_A.seq seq_chains/4mt4_B.seq
bin/seqid.py seq_chains/4myc_A.seq seq_chains/4myc_B.seq
bin/seqid.py seq_chains/4o7g_A.seq seq_chains/4o7g_B.seq
bin/seqid.py seq_chains/4o93_A.seq seq_chains/4o93_B.seq
bin/seqid.py seq_chains/4o9u_A.seq seq_chains/4o9u_B.seq
bin/seqid.py seq_chains/4oh3_A.seq seq_chains/4oh3_B.seq
bin/seqid.py seq_chains/4p6v_B.seq seq_chains/4p6v_D.seq
bin/seqid.py seq_chains/4p6v_B.seq seq_chains/4p6v_E.seq
bin/seqid.py seq_chains/4p6v_C.seq seq_chains/4p6v_D.seq
bin/seqid.py seq_chains/4p6v_C.seq seq_chains/4p6v_E.seq
bin/seqid.py seq_chains/4p6v_C.seq seq_chains/4p6v_F.seq
bin/seqid.py seq_chains/4p6v_D.seq seq_chains/4p6v_E.seq
bin/seqid.py seq_chains/4p6v_E.seq seq_chains/4p6v_F.seq
bin/seqid.py seq_chains/4phz_A.seq seq_chains/4phz_B.seq
bin/seqid.py seq_chains/4pi0_A.seq seq_chains/4pi0_B.seq
bin/seqid.py seq_chains/4pi2_F.seq seq_chains/4pi2_G.seq
bin/seqid.py seq_chains/4pir_B.seq seq_chains/4pir_C.seq
bin/seqid.py seq_chains/4pj0_B.seq seq_chains/4pj0_D.seq
bin/seqid.py seq_chains/4pl0_A.seq seq_chains/4pl0_B.seq
bin/seqid.py seq_chains/4q2g_A.seq seq_chains/4q2g_B.seq
bin/seqid.py seq_chains/4q35_A.seq seq_chains/4q35_B.seq
bin/seqid.py seq_chains/4qnd_A.seq seq_chains/4qnd_B.seq
bin/seqid.py seq_chains/4qnz_A.seq seq_chains/4qnz_B.seq
bin/seqid.py seq_chains/4qtn_A.seq seq_chains/4qtn_C.seq
bin/seqid.py seq_chains/4r1i_A.seq seq_chains/4r1i_B.seq
bin/seqid.py seq_chains/4rdq_A.seq seq_chains/4rdq_B.seq
bin/seqid.py seq_chains/4rfs_S.seq seq_chains/4rfs_T.seq
bin/seqid.py seq_chains/4ri2_A.seq seq_chains/4ri2_B.seq
bin/seqid.py seq_chains/4rjw_A.seq seq_chains/4rjw_B.seq
bin/seqid.py seq_chains/4rng_A.seq seq_chains/4rng_C.seq
bin/seqid.py seq_chains/4rp9_A.seq seq_chains/4rp9_B.seq
bin/seqid.py seq_chains/4ry2_A.seq seq_chains/4ry2_B.seq
bin/seqid.py seq_chains/4tll_A.seq seq_chains/4tll_D.seq
bin/seqid.py seq_chains/4tlm_A.seq seq_chains/4tlm_B.seq
bin/seqid.py seq_chains/4tpg_A.seq seq_chains/4tpg_E.seq
bin/seqid.py seq_chains/4uc1_A.seq seq_chains/4uc1_B.seq
bin/seqid.py seq_chains/4uv3_A.seq seq_chains/4uv3_B.seq
bin/seqid.py seq_chains/4v1f_A.seq seq_chains/4v1f_B.seq
bin/seqid.py seq_chains/4wd7_A.seq seq_chains/4wd7_B.seq
bin/seqid.py seq_chains/4wis_A.seq seq_chains/4wis_B.seq
bin/seqid.py seq_chains/4wz7_A.seq seq_chains/4wz7_C.seq
bin/seqid.py seq_chains/4wz7_A.seq seq_chains/4wz7_F.seq
bin/seqid.py seq_chains/4wz7_B.seq seq_chains/4wz7_D.seq
bin/seqid.py seq_chains/4wz7_B.seq seq_chains/4wz7_F.seq
bin/seqid.py seq_chains/4wz7_B.seq seq_chains/4wz7_O.seq
bin/seqid.py seq_chains/4wz7_C.seq seq_chains/4wz7_F.seq
bin/seqid.py seq_chains/4wz7_C.seq seq_chains/4wz7_O.seq
bin/seqid.py seq_chains/4wz7_F.seq seq_chains/4wz7_O.seq
bin/seqid.py seq_chains/4x5n_C.seq seq_chains/4x5n_D.seq
bin/seqid.py seq_chains/4xig_M.seq seq_chains/4xig_N.seq
bin/seqid.py seq_chains/4xk8_A.seq seq_chains/4xk8_B.seq
bin/seqid.py seq_chains/4xk8_H.seq seq_chains/4xk8_I.seq
bin/seqid.py seq_chains/4xt1_A.seq seq_chains/4xt1_B.seq
bin/seqid.py seq_chains/4xt3_A.seq seq_chains/4xt3_B.seq
bin/seqid.py seq_chains/4xtn_A.seq seq_chains/4xtn_B.seq
bin/seqid.py seq_chains/4xu4_A.seq seq_chains/4xu4_B.seq
bin/seqid.py seq_chains/4xyd_A.seq seq_chains/4xyd_B.seq
bin/seqid.py seq_chains/4y1k_A.seq seq_chains/4y1k_B.seq
bin/seqid.py seq_chains/4y28_1.seq seq_chains/4y28_4.seq
bin/seqid.py seq_chains/4y7k_A.seq seq_chains/4y7k_B.seq
bin/seqid.py seq_chains/4yms_C.seq seq_chains/4yms_D.seq
bin/seqid.py seq_chains/4yuu_A.seq seq_chains/4yuu_C.seq
bin/seqid.py seq_chains/4yuu_C.seq seq_chains/4yuu_J.seq
bin/seqid.py seq_chains/4yuu_e.seq seq_chains/4yuu_f.seq
bin/seqid.py seq_chains/4yzf_A.seq seq_chains/4yzf_B.seq
bin/seqid.py seq_chains/4yzi_A.seq seq_chains/4yzi_B.seq
bin/seqid.py seq_chains/4z90_A.seq seq_chains/4z90_B.seq
bin/seqid.py seq_chains/4ziv_A.seq seq_chains/4ziv_B.seq
bin/seqid.py seq_chains/5a1s_C.seq seq_chains/5a1s_D.seq
bin/seqid.py seq_chains/5a40_A.seq seq_chains/5a40_B.seq
bin/seqid.py seq_chains/5a63_A.seq seq_chains/5a63_C.seq
bin/seqid.py seq_chains/5a63_B.seq seq_chains/5a63_C.seq
bin/seqid.py seq_chains/5a63_B.seq seq_chains/5a63_D.seq
bin/seqid.py seq_chains/5aex_A.seq seq_chains/5aex_B.seq
bin/seqid.py seq_chains/5aji_A.seq seq_chains/5aji_B.seq
bin/seqid.py seq_chains/5aww_E.seq seq_chains/5aww_Y.seq
bin/seqid.py seq_chains/5aww_G.seq seq_chains/5aww_Y.seq
bin/seqid.py seq_chains/5bun_A.seq seq_chains/5bun_C.seq
bin/seqid.py seq_chains/5but_I.seq seq_chains/5but_J.seq
bin/seqid.py seq_chains/5c76_A.seq seq_chains/5c76_D.seq
bin/seqid.py seq_chains/5cbf_A.seq seq_chains/5cbf_B.seq
bin/seqid.py seq_chains/5ckr_A.seq seq_chains/5ckr_B.seq
bin/seqid.py seq_chains/5ctg_A.seq seq_chains/5ctg_B.seq
bin/seqid.py seq_chains/5d3m_C.seq seq_chains/5d3m_D.seq
bin/seqid.py seq_chains/5d92_B.seq seq_chains/5d92_C.seq
bin/seqid.py seq_chains/5dn6_J.seq seq_chains/5dn6_K.seq
bin/seqid.py seq_chains/5do7_A.seq seq_chains/5do7_B.seq
bin/seqid.py seq_chains/5doq_A.seq seq_chains/5doq_B.seq
bin/seqid.py seq_chains/5doq_A.seq seq_chains/5doq_C.seq
bin/seqid.py seq_chains/5dqq_A.seq seq_chains/5dqq_B.seq
bin/seqid.py seq_chains/5dwy_A.seq seq_chains/5dwy_B.seq
bin/seqid.py seq_chains/5ec5_A.seq seq_chains/5ec5_B.seq
bin/seqid.py seq_chains/5eik_A.seq seq_chains/5eik_B.seq
bin/seqid.py seq_chains/5eke_A.seq seq_chains/5eke_C.seq
bin/seqid.py seq_chains/5eul_A.seq seq_chains/5eul_Y.seq
bin/seqid.py seq_chains/5eul_E.seq seq_chains/5eul_Y.seq
bin/seqid.py seq_chains/5fn2_B.seq seq_chains/5fn2_C.seq
bin/seqid.py seq_chains/5gjv_A.seq seq_chains/5gjv_E.seq
bin/seqid.py seq_chains/5gjw_A.seq seq_chains/5gjw_E.seq
bin/seqid.py seq_chains/5hi9_A.seq seq_chains/5hi9_B.seq
bin/seqid.py seq_chains/5i32_A.seq seq_chains/5i32_C.seq
bin/seqid.py seq_chains/5i6c_A.seq seq_chains/5i6c_B.seq
bin/seqid.py seq_chains/5irx_C.seq seq_chains/5irx_E.seq
bin/seqid.py seq_chains/5iuy_A.seq seq_chains/5iuy_C.seq
bin/seqid.py seq_chains/5iva_A.seq seq_chains/5iva_B.seq
bin/seqid.py seq_chains/5iwr_A.seq seq_chains/5iwr_C.seq
bin/seqid.py seq_chains/5iws_A.seq seq_chains/5iws_B.seq
bin/seqid.py seq_chains/5j4i_A.seq seq_chains/5j4i_B.seq
bin/seqid.py seq_chains/5jzt_A.seq seq_chains/5jzt_B.seq
bin/seqid.py seq_chains/5k47_A.seq seq_chains/5k47_B.seq
bin/seqid.py seq_chains/5kbn_A.seq seq_chains/5kbn_B.seq
bin/seqid.py seq_chains/5kbs_A.seq seq_chains/5kbs_B.seq
bin/seqid.py seq_chains/5klb_A.seq seq_chains/5klb_C.seq
bin/seqid.py seq_chains/5l25_A.seq seq_chains/5l25_B.seq
bin/seqid.py seq_chains/5lc5_A.seq seq_chains/5lc5_H.seq
bin/seqid.py seq_chains/5lc5_A.seq seq_chains/5lc5_J.seq
bin/seqid.py seq_chains/5lc5_A.seq seq_chains/5lc5_K.seq
bin/seqid.py seq_chains/5lc5_c.seq seq_chains/5lc5_d.seq
bin/seqid.py seq_chains/5lc5_g.seq seq_chains/5lc5_h.seq
bin/seqid.py seq_chains/5lc5_H.seq seq_chains/5lc5_a.seq
bin/seqid.py seq_chains/5lc5_H.seq seq_chains/5lc5_J.seq
bin/seqid.py seq_chains/5lc5_H.seq seq_chains/5lc5_Z.seq
bin/seqid.py seq_chains/5lc5_J.seq seq_chains/5lc5_K.seq
bin/seqid.py seq_chains/5lc5_J.seq seq_chains/5lc5_N.seq
bin/seqid.py seq_chains/5lc5_K.seq seq_chains/5lc5_L.seq
bin/seqid.py seq_chains/5lc5_K.seq seq_chains/5lc5_N.seq
bin/seqid.py seq_chains/5lc5_L.seq seq_chains/5lc5_m.seq
bin/seqid.py seq_chains/5lc5_L.seq seq_chains/5lc5_M.seq
bin/seqid.py seq_chains/5lc5_L.seq seq_chains/5lc5_N.seq
bin/seqid.py seq_chains/5lc5_L.seq seq_chains/5lc5_Y.seq
bin/seqid.py seq_chains/5lc5_M.seq seq_chains/5lc5_f.seq
bin/seqid.py seq_chains/5lc5_M.seq seq_chains/5lc5_g.seq
bin/seqid.py seq_chains/5lc5_M.seq seq_chains/5lc5_m.seq
bin/seqid.py seq_chains/5lc5_M.seq seq_chains/5lc5_N.seq
bin/seqid.py seq_chains/5lc5_N.seq seq_chains/5lc5_d.seq
bin/seqid.py seq_chains/5ldw_A.seq seq_chains/5ldw_H.seq
bin/seqid.py seq_chains/5sv0_A.seq seq_chains/5sv0_B.seq
bin/seqid.py seq_chains/5sv9_A.seq seq_chains/5sv9_B.seq
bin/seqid.py seq_chains/5svk_A.seq seq_chains/5svk_B.seq
bin/seqid.py seq_chains/5sy1_A.seq seq_chains/5sy1_B.seq
