wget http://www.uniprot.org/uniprot/A0A024R0C6.fasta
wget http://www.uniprot.org/uniprot/A0A024RBC0.fasta
wget http://www.uniprot.org/uniprot/A0A064S5H4.fasta
wget http://www.uniprot.org/uniprot/A0A066QMU1.fasta
wget http://www.uniprot.org/uniprot/A0FGR8.fasta
wget http://www.uniprot.org/uniprot/A0N0P2.fasta
wget http://www.uniprot.org/uniprot/A1L4F5.fasta
wget http://www.uniprot.org/uniprot/A1Z0Q5.fasta
wget http://www.uniprot.org/uniprot/A3PGX8.fasta
wget http://www.uniprot.org/uniprot/A5GZW8.fasta
wget http://www.uniprot.org/uniprot/A8ASG5.fasta
wget http://www.uniprot.org/uniprot/C3TQQ7.fasta
wget http://www.uniprot.org/uniprot/C4X1R9.fasta
wget http://www.uniprot.org/uniprot/D0VWV4.fasta
wget http://www.uniprot.org/uniprot/D5ANZ2.fasta
wget http://www.uniprot.org/uniprot/D5ANZ3.fasta
wget http://www.uniprot.org/uniprot/D5ANZ4.fasta
wget http://www.uniprot.org/uniprot/E1WFA0.fasta
wget http://www.uniprot.org/uniprot/E9M2N4.fasta
wget http://www.uniprot.org/uniprot/G1UBD1.fasta
wget http://www.uniprot.org/uniprot/H7C748.fasta
wget http://www.uniprot.org/uniprot/J7Q602.fasta
wget http://www.uniprot.org/uniprot/O00206.fasta
wget http://www.uniprot.org/uniprot/O08603.fasta
wget http://www.uniprot.org/uniprot/O14684.fasta
wget http://www.uniprot.org/uniprot/O14763.fasta
wget http://www.uniprot.org/uniprot/O15455.fasta
wget http://www.uniprot.org/uniprot/O15517.fasta
wget http://www.uniprot.org/uniprot/O19470.fasta
wget http://www.uniprot.org/uniprot/O19707.fasta
wget http://www.uniprot.org/uniprot/O27564.fasta
wget http://www.uniprot.org/uniprot/O29883.fasta
wget http://www.uniprot.org/uniprot/O35235.fasta
wget http://www.uniprot.org/uniprot/O43570.fasta
wget http://www.uniprot.org/uniprot/O43752.fasta
wget http://www.uniprot.org/uniprot/O46345.fasta
wget http://www.uniprot.org/uniprot/O54709.fasta
wget http://www.uniprot.org/uniprot/O60894.fasta
wget http://www.uniprot.org/uniprot/O60895.fasta
wget http://www.uniprot.org/uniprot/O60989.fasta
wget http://www.uniprot.org/uniprot/O65938.fasta
wget http://www.uniprot.org/uniprot/O75024.fasta
wget http://www.uniprot.org/uniprot/O75326.fasta
wget http://www.uniprot.org/uniprot/O75379.fasta
wget http://www.uniprot.org/uniprot/O75455.fasta
wget http://www.uniprot.org/uniprot/O75899.fasta
wget http://www.uniprot.org/uniprot/O78189.fasta
wget http://www.uniprot.org/uniprot/O95292.fasta
wget http://www.uniprot.org/uniprot/O97148.fasta
wget http://www.uniprot.org/uniprot/P00125.fasta
wget http://www.uniprot.org/uniprot/P00130.fasta
wget http://www.uniprot.org/uniprot/P00157.fasta
wget http://www.uniprot.org/uniprot/P00163.fasta
wget http://www.uniprot.org/uniprot/P00415.fasta
wget http://www.uniprot.org/uniprot/P00423.fasta
wget http://www.uniprot.org/uniprot/P00430.fasta
wget http://www.uniprot.org/uniprot/P00803.fasta
wget http://www.uniprot.org/uniprot/P01730.fasta
wget http://www.uniprot.org/uniprot/P01731.fasta
wget http://www.uniprot.org/uniprot/P01732.fasta
wget http://www.uniprot.org/uniprot/P01889.fasta
wget http://www.uniprot.org/uniprot/P01903.fasta
wget http://www.uniprot.org/uniprot/P01910.fasta
wget http://www.uniprot.org/uniprot/P01911.fasta
wget http://www.uniprot.org/uniprot/P01912.fasta
wget http://www.uniprot.org/uniprot/P01921.fasta
wget http://www.uniprot.org/uniprot/P02699.fasta
wget http://www.uniprot.org/uniprot/P02724.fasta
wget http://www.uniprot.org/uniprot/P02730.fasta
wget http://www.uniprot.org/uniprot/P02786.fasta
wget http://www.uniprot.org/uniprot/P02916.fasta
wget http://www.uniprot.org/uniprot/P02920.fasta
wget http://www.uniprot.org/uniprot/P02929.fasta
wget http://www.uniprot.org/uniprot/P03171.fasta
wget http://www.uniprot.org/uniprot/P03376.fasta
wget http://www.uniprot.org/uniprot/P03661.fasta
wget http://www.uniprot.org/uniprot/P03879.fasta
wget http://www.uniprot.org/uniprot/P04038.fasta
wget http://www.uniprot.org/uniprot/P04166.fasta
wget http://www.uniprot.org/uniprot/P04228.fasta
wget http://www.uniprot.org/uniprot/P04229.fasta
wget http://www.uniprot.org/uniprot/P04233.fasta
wget http://www.uniprot.org/uniprot/P04578.fasta
wget http://www.uniprot.org/uniprot/P04580.fasta
wget http://www.uniprot.org/uniprot/P04629.fasta
wget http://www.uniprot.org/uniprot/P05067.fasta
wget http://www.uniprot.org/uniprot/P05362.fasta
wget http://www.uniprot.org/uniprot/P05710.fasta
wget http://www.uniprot.org/uniprot/P05877.fasta
wget http://www.uniprot.org/uniprot/P06008.fasta
wget http://www.uniprot.org/uniprot/P06009.fasta
wget http://www.uniprot.org/uniprot/P06010.fasta
wget http://www.uniprot.org/uniprot/P06030.fasta
wget http://www.uniprot.org/uniprot/P06343.fasta
wget http://www.uniprot.org/uniprot/P06344.fasta
wget http://www.uniprot.org/uniprot/P06609.fasta
wget http://www.uniprot.org/uniprot/P07001.fasta
wget http://www.uniprot.org/uniprot/P07141.fasta
wget http://www.uniprot.org/uniprot/P07470.fasta
wget http://www.uniprot.org/uniprot/P07975.fasta
wget http://www.uniprot.org/uniprot/P08306.fasta
wget http://www.uniprot.org/uniprot/P08395.fasta
wget http://www.uniprot.org/uniprot/P08887.fasta
wget http://www.uniprot.org/uniprot/P08921.fasta
wget http://www.uniprot.org/uniprot/P09391.fasta
wget http://www.uniprot.org/uniprot/P09581.fasta
wget http://www.uniprot.org/uniprot/P09601.fasta
wget http://www.uniprot.org/uniprot/P0A334.fasta
wget http://www.uniprot.org/uniprot/P0A406.fasta
wget http://www.uniprot.org/uniprot/P0A407.fasta
wget http://www.uniprot.org/uniprot/P0A426.fasta
wget http://www.uniprot.org/uniprot/P0A428.fasta
wget http://www.uniprot.org/uniprot/P0A430.fasta
wget http://www.uniprot.org/uniprot/P0A5Z9.fasta
wget http://www.uniprot.org/uniprot/P0A8Q1.fasta
wget http://www.uniprot.org/uniprot/P0A8Q5.fasta
wget http://www.uniprot.org/uniprot/P0AAI4.fasta
wget http://www.uniprot.org/uniprot/P0AAJ4.fasta
wget http://www.uniprot.org/uniprot/P0AB69.fasta
wget http://www.uniprot.org/uniprot/P0AB99.fasta
wget http://www.uniprot.org/uniprot/P0ABI8.fasta
wget http://www.uniprot.org/uniprot/P0ABJ1.fasta
wget http://www.uniprot.org/uniprot/P0ABJ3.fasta
wget http://www.uniprot.org/uniprot/P0ABN4.fasta
wget http://www.uniprot.org/uniprot/P0AC46.fasta
wget http://www.uniprot.org/uniprot/P0AEJ5.fasta
wget http://www.uniprot.org/uniprot/P0AEK9.fasta
wget http://www.uniprot.org/uniprot/P0AG97.fasta
wget http://www.uniprot.org/uniprot/P0AG99.fasta
wget http://www.uniprot.org/uniprot/P0AGA5.fasta
wget http://www.uniprot.org/uniprot/P0C0S3.fasta
wget http://www.uniprot.org/uniprot/P0C0Y7.fasta
wget http://www.uniprot.org/uniprot/P0C0Y8.fasta
wget http://www.uniprot.org/uniprot/P0C0Y9.fasta
wget http://www.uniprot.org/uniprot/P0C1D4.fasta
wget http://www.uniprot.org/uniprot/P0C532.fasta
wget http://www.uniprot.org/uniprot/P10300.fasta
wget http://www.uniprot.org/uniprot/P10415.fasta
wget http://www.uniprot.org/uniprot/P10912.fasta
wget http://www.uniprot.org/uniprot/P12023.fasta
wget http://www.uniprot.org/uniprot/P12238.fasta
wget http://www.uniprot.org/uniprot/P12239.fasta
wget http://www.uniprot.org/uniprot/P12241.fasta
wget http://www.uniprot.org/uniprot/P12319.fasta
wget http://www.uniprot.org/uniprot/P13473.fasta
wget http://www.uniprot.org/uniprot/P13591.fasta
wget http://www.uniprot.org/uniprot/P13596.fasta
wget http://www.uniprot.org/uniprot/P13599.fasta
wget http://www.uniprot.org/uniprot/P13688.fasta
wget http://www.uniprot.org/uniprot/P13726.fasta
wget http://www.uniprot.org/uniprot/P13738.fasta
wget http://www.uniprot.org/uniprot/P13747.fasta
wget http://www.uniprot.org/uniprot/P13760.fasta
wget http://www.uniprot.org/uniprot/P14335.fasta
wget http://www.uniprot.org/uniprot/P14434.fasta
wget http://www.uniprot.org/uniprot/P14438.fasta
wget http://www.uniprot.org/uniprot/P14483.fasta
wget http://www.uniprot.org/uniprot/P14769.fasta
wget http://www.uniprot.org/uniprot/P15151.fasta
wget http://www.uniprot.org/uniprot/P15260.fasta
wget http://www.uniprot.org/uniprot/P15746.fasta
wget http://www.uniprot.org/uniprot/P15813.fasta
wget http://www.uniprot.org/uniprot/P16389.fasta
wget http://www.uniprot.org/uniprot/P16410.fasta
wget http://www.uniprot.org/uniprot/P17342.fasta
wget http://www.uniprot.org/uniprot/P17413.fasta
wget http://www.uniprot.org/uniprot/P17798.fasta
wget http://www.uniprot.org/uniprot/P18011.fasta
wget http://www.uniprot.org/uniprot/P19235.fasta
wget http://www.uniprot.org/uniprot/P19438.fasta
wget http://www.uniprot.org/uniprot/P19491.fasta
wget http://www.uniprot.org/uniprot/P19492.fasta
wget http://www.uniprot.org/uniprot/P19493.fasta
wget http://www.uniprot.org/uniprot/P20333.fasta
wget http://www.uniprot.org/uniprot/P21579.fasta
wget http://www.uniprot.org/uniprot/P21707.fasta
wget http://www.uniprot.org/uniprot/P23188.fasta
wget http://www.uniprot.org/uniprot/P23230.fasta
wget http://www.uniprot.org/uniprot/P23545.fasta
wget http://www.uniprot.org/uniprot/P23577.fasta
wget http://www.uniprot.org/uniprot/P23833.fasta
wget http://www.uniprot.org/uniprot/P25942.fasta
wget http://www.uniprot.org/uniprot/P26010.fasta
wget http://www.uniprot.org/uniprot/P26663.fasta
wget http://www.uniprot.org/uniprot/P26678.fasta
wget http://www.uniprot.org/uniprot/P26715.fasta
wget http://www.uniprot.org/uniprot/P26718.fasta
wget http://www.uniprot.org/uniprot/P27037.fasta
wget http://www.uniprot.org/uniprot/P27299.fasta
wget http://www.uniprot.org/uniprot/P27338.fasta
wget http://www.uniprot.org/uniprot/P28068.fasta
wget http://www.uniprot.org/uniprot/P29254.fasta
wget http://www.uniprot.org/uniprot/P29255.fasta
wget http://www.uniprot.org/uniprot/P29317.fasta
wget http://www.uniprot.org/uniprot/P29965.fasta
wget http://www.uniprot.org/uniprot/P31109.fasta
wget http://www.uniprot.org/uniprot/P32851.fasta
wget http://www.uniprot.org/uniprot/P32867.fasta
wget http://www.uniprot.org/uniprot/P33517.fasta
wget http://www.uniprot.org/uniprot/P33650.fasta
wget http://www.uniprot.org/uniprot/P35179.fasta
wget http://www.uniprot.org/uniprot/P35439.fasta
wget http://www.uniprot.org/uniprot/P36655.fasta
wget http://www.uniprot.org/uniprot/P36894.fasta
wget http://www.uniprot.org/uniprot/P37019.fasta
wget http://www.uniprot.org/uniprot/P37277.fasta
wget http://www.uniprot.org/uniprot/P38134.fasta
wget http://www.uniprot.org/uniprot/P38353.fasta
wget http://www.uniprot.org/uniprot/P40189.fasta
wget http://www.uniprot.org/uniprot/P40416.fasta
wget http://www.uniprot.org/uniprot/P41143.fasta
wget http://www.uniprot.org/uniprot/P42081.fasta
wget http://www.uniprot.org/uniprot/P42196.fasta
wget http://www.uniprot.org/uniprot/P42259.fasta
wget http://www.uniprot.org/uniprot/P43627.fasta
wget http://www.uniprot.org/uniprot/P46096.fasta
wget http://www.uniprot.org/uniprot/P46925.fasta
wget http://www.uniprot.org/uniprot/P48357.fasta
wget http://www.uniprot.org/uniprot/P48551.fasta
wget http://www.uniprot.org/uniprot/P49771.fasta
wget http://www.uniprot.org/uniprot/P50369.fasta
wget http://www.uniprot.org/uniprot/P50591.fasta
wget http://www.uniprot.org/uniprot/P51572.fasta
wget http://www.uniprot.org/uniprot/P51693.fasta
wget http://www.uniprot.org/uniprot/P51765.fasta
wget http://www.uniprot.org/uniprot/P52799.fasta
wget http://www.uniprot.org/uniprot/P52871.fasta
wget http://www.uniprot.org/uniprot/P54116.fasta
wget http://www.uniprot.org/uniprot/P54582.fasta
wget http://www.uniprot.org/uniprot/P54763.fasta
wget http://www.uniprot.org/uniprot/P54764.fasta
wget http://www.uniprot.org/uniprot/P60033.fasta
wget http://www.uniprot.org/uniprot/P60460.fasta
wget http://www.uniprot.org/uniprot/P60844.fasta
wget http://www.uniprot.org/uniprot/P61829.fasta
wget http://www.uniprot.org/uniprot/P63027.fasta
wget http://www.uniprot.org/uniprot/P63045.fasta
wget http://www.uniprot.org/uniprot/P63142.fasta
wget http://www.uniprot.org/uniprot/P63360.fasta
wget http://www.uniprot.org/uniprot/P68185.fasta
wget http://www.uniprot.org/uniprot/P68701.fasta
wget http://www.uniprot.org/uniprot/P69054.fasta
wget http://www.uniprot.org/uniprot/P69787.fasta
wget http://www.uniprot.org/uniprot/P77173.fasta
wget http://www.uniprot.org/uniprot/P77921.fasta
wget http://www.uniprot.org/uniprot/P78310.fasta
wget http://www.uniprot.org/uniprot/P78380.fasta
wget http://www.uniprot.org/uniprot/P80667.fasta
wget http://www.uniprot.org/uniprot/P82543.fasta
wget http://www.uniprot.org/uniprot/P83792.fasta
wget http://www.uniprot.org/uniprot/P83793.fasta
wget http://www.uniprot.org/uniprot/P83795.fasta
wget http://www.uniprot.org/uniprot/P83796.fasta
wget http://www.uniprot.org/uniprot/P83797.fasta
wget http://www.uniprot.org/uniprot/P95673.fasta
wget http://www.uniprot.org/uniprot/P97253.fasta
wget http://www.uniprot.org/uniprot/P98002.fasta
wget http://www.uniprot.org/uniprot/P9WI81.fasta
wget http://www.uniprot.org/uniprot/Q00471.fasta
wget http://www.uniprot.org/uniprot/Q01974.fasta
wget http://www.uniprot.org/uniprot/Q03322.fasta
wget http://www.uniprot.org/uniprot/Q03736.fasta
wget http://www.uniprot.org/uniprot/Q04230.fasta
wget http://www.uniprot.org/uniprot/Q04651.fasta
wget http://www.uniprot.org/uniprot/Q07108.fasta
wget http://www.uniprot.org/uniprot/Q07812.fasta
wget http://www.uniprot.org/uniprot/Q07813.fasta
wget http://www.uniprot.org/uniprot/Q07817.fasta
wget http://www.uniprot.org/uniprot/Q07820.fasta
wget http://www.uniprot.org/uniprot/Q08362.fasta
wget http://www.uniprot.org/uniprot/Q10589.fasta
wget http://www.uniprot.org/uniprot/Q12983.fasta
wget http://www.uniprot.org/uniprot/Q13002.fasta
wget http://www.uniprot.org/uniprot/Q13241.fasta
wget http://www.uniprot.org/uniprot/Q15223.fasta
wget http://www.uniprot.org/uniprot/Q16602.fasta
wget http://www.uniprot.org/uniprot/Q16611.fasta
wget http://www.uniprot.org/uniprot/Q16849.fasta
wget http://www.uniprot.org/uniprot/Q16873.fasta
wget http://www.uniprot.org/uniprot/Q1PLH8.fasta
wget http://www.uniprot.org/uniprot/Q29983.fasta
wget http://www.uniprot.org/uniprot/Q30070.fasta
wget http://www.uniprot.org/uniprot/Q30154.fasta
wget http://www.uniprot.org/uniprot/Q30201.fasta
wget http://www.uniprot.org/uniprot/Q31135.fasta
wget http://www.uniprot.org/uniprot/Q31163.fasta
wget http://www.uniprot.org/uniprot/Q31604.fasta
wget http://www.uniprot.org/uniprot/Q31615.fasta
wget http://www.uniprot.org/uniprot/Q32WE6.fasta
wget http://www.uniprot.org/uniprot/Q3J170.fasta
wget http://www.uniprot.org/uniprot/Q3J1A5.fasta
wget http://www.uniprot.org/uniprot/Q3J1A6.fasta
wget http://www.uniprot.org/uniprot/Q41372.fasta
wget http://www.uniprot.org/uniprot/Q42496.fasta
wget http://www.uniprot.org/uniprot/Q47065.fasta
wget http://www.uniprot.org/uniprot/Q4GWN8.fasta
wget http://www.uniprot.org/uniprot/Q57817.fasta
wget http://www.uniprot.org/uniprot/Q58812.fasta
wget http://www.uniprot.org/uniprot/Q5D1W8.fasta
wget http://www.uniprot.org/uniprot/Q5M4H8.fasta
wget http://www.uniprot.org/uniprot/Q5SSZ7.fasta
wget http://www.uniprot.org/uniprot/Q5VWS7.fasta
wget http://www.uniprot.org/uniprot/Q5YJJ6.fasta
wget http://www.uniprot.org/uniprot/Q60175.fasta
wget http://www.uniprot.org/uniprot/Q60362.fasta
wget http://www.uniprot.org/uniprot/Q603F1.fasta
wget http://www.uniprot.org/uniprot/Q607G3.fasta
wget http://www.uniprot.org/uniprot/Q63690.fasta
wget http://www.uniprot.org/uniprot/Q67132.fasta
wget http://www.uniprot.org/uniprot/Q69091.fasta
wget http://www.uniprot.org/uniprot/Q6EMS9.fasta
wget http://www.uniprot.org/uniprot/Q6FH58.fasta
wget http://www.uniprot.org/uniprot/Q6GTR6.fasta
wget http://www.uniprot.org/uniprot/Q6GTX8.fasta
wget http://www.uniprot.org/uniprot/Q6S3H2.fasta
wget http://www.uniprot.org/uniprot/Q6S3I0.fasta
wget http://www.uniprot.org/uniprot/Q72JK2.fasta
wget http://www.uniprot.org/uniprot/Q72JK3.fasta
wget http://www.uniprot.org/uniprot/Q75ME0.fasta
wget http://www.uniprot.org/uniprot/Q786F2.fasta
wget http://www.uniprot.org/uniprot/Q7DGD4.fasta
wget http://www.uniprot.org/uniprot/Q7JAT3.fasta
wget http://www.uniprot.org/uniprot/Q7NDN8.fasta
wget http://www.uniprot.org/uniprot/Q7Z6A9.fasta
wget http://www.uniprot.org/uniprot/Q80W68.fasta
wget http://www.uniprot.org/uniprot/Q85082.fasta
wget http://www.uniprot.org/uniprot/Q8CM25.fasta
wget http://www.uniprot.org/uniprot/Q8DGB4.fasta
wget http://www.uniprot.org/uniprot/Q8DHA7.fasta
wget http://www.uniprot.org/uniprot/Q8DHE6.fasta
wget http://www.uniprot.org/uniprot/Q8DIF8.fasta
wget http://www.uniprot.org/uniprot/Q8DIN9.fasta
wget http://www.uniprot.org/uniprot/Q8DIQ0.fasta
wget http://www.uniprot.org/uniprot/Q8DIQ1.fasta
wget http://www.uniprot.org/uniprot/Q8DJ43.fasta
wget http://www.uniprot.org/uniprot/Q8DJZ6.fasta
wget http://www.uniprot.org/uniprot/Q8DKP6.fasta
wget http://www.uniprot.org/uniprot/Q8EHE6.fasta
wget http://www.uniprot.org/uniprot/Q8IUH5.fasta
wget http://www.uniprot.org/uniprot/Q8KRK5.fasta
wget http://www.uniprot.org/uniprot/Q8KRV3.fasta
wget http://www.uniprot.org/uniprot/Q8RBX6.fasta
wget http://www.uniprot.org/uniprot/Q8ZRP8.fasta
wget http://www.uniprot.org/uniprot/Q91V35.fasta
wget http://www.uniprot.org/uniprot/Q91XB0.fasta
wget http://www.uniprot.org/uniprot/Q92692.fasta
wget http://www.uniprot.org/uniprot/Q92838.fasta
wget http://www.uniprot.org/uniprot/Q92956.fasta
wget http://www.uniprot.org/uniprot/Q96KS6.fasta
wget http://www.uniprot.org/uniprot/Q96NY8.fasta
wget http://www.uniprot.org/uniprot/Q97SC2.fasta
wget http://www.uniprot.org/uniprot/Q9BYF1.fasta
wget http://www.uniprot.org/uniprot/Q9H2X3.fasta
wget http://www.uniprot.org/uniprot/Q9IH62.fasta
wget http://www.uniprot.org/uniprot/Q9JHN9.fasta
wget http://www.uniprot.org/uniprot/Q9NNX6.fasta
wget http://www.uniprot.org/uniprot/Q9NP99.fasta
wget http://www.uniprot.org/uniprot/Q9NZN1.fasta
wget http://www.uniprot.org/uniprot/Q9QUK6.fasta
wget http://www.uniprot.org/uniprot/Q9R174.fasta
wget http://www.uniprot.org/uniprot/Q9TP17.fasta
wget http://www.uniprot.org/uniprot/Q9TP70.fasta
wget http://www.uniprot.org/uniprot/Q9UBS5.fasta
wget http://www.uniprot.org/uniprot/Q9UIB8.fasta
wget http://www.uniprot.org/uniprot/Q9W4T9.fasta
wget http://www.uniprot.org/uniprot/Q9Y3E5.fasta
wget http://www.uniprot.org/uniprot/Q9Y5Y6.fasta
wget http://www.uniprot.org/uniprot/Q9Z270.fasta
wget http://www.uniprot.org/uniprot/R2NGE2.fasta
wget http://www.uniprot.org/uniprot/UPI0000110850.fasta
wget http://www.uniprot.org/uniprot/W8U272.fasta
wget http://www.uniprot.org/uniprot/X2JCF8.fasta
