~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1a3a.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1a3a.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1a6a.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1a6a.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1a6z.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1a6z.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1afo.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1afo.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1aij.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1aij.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1aij.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1akj.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1akj.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1b12.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1b12.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1bcc.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1bcc.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1bcc.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1bx2.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1bx2.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1c16.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1c16.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1c17.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1c17.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1cdc.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1cdc.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1d4v.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1d4v.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1d5z.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1d5z.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1d9k.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1d9k.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1dan.ent.gz T
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1dan.ent.gz U
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1de4.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1de4.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1de4.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1dqt.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1dqt.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1dxr.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1dxr.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e14.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e14.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e6d.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e6d.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e6d.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e9r.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1e9r.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1eaj.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1eaj.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1eaw.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1eaw.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1efx.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1efx.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1epf.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1epf.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ern.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ern.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ext.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ext.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1eys.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1eys.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1f3j.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1f3j.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1f6n.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1f6n.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fft.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fft.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fft.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fg9.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fg9.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fjr.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fjr.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1flc.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1flc.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fne.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fne.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fnp.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fnp.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fv1.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1fv1.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1g8q.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1g8q.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1h2s.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1h2s.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hgi.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hgi.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hsa.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hsa.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hvv.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hvv.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hyr.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1hyr.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1i85.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1i85.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1i85.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1i8l.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1i8l.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1id1.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1id1.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1iie.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1iie.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1im9.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1im9.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1j88.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1j88.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ja3.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ja3.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz K
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jb0.ent.gz X
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jdp.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jdp.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jfm.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jfm.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgw.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgw.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgw.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgx.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgx.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgy.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jgy.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jh0.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jh0.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jh0.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jk8.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jk8.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jma.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jma.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1joy.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1joy.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jqq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1jqq.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1k2d.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1k2d.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1k6n.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1k6n.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1k9i.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1k9i.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kby.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kby.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kby.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kcg.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kcg.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kf6.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kf6.ent.gz P
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kgy.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kgy.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1klu.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1klu.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kpl.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kpl.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kqf.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1kqf.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1l7v.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1l7v.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1lgh.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1lgh.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1lgh.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1lnq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1lnq.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m56.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m56.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m56.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m57.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m57.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m57.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1m57.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1miq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1miq.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1mps.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1mps.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1mq8.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1mq8.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1muj.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1muj.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1n45.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1n45.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1n7s.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1n7s.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ncn.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ncn.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ng7.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ng7.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1nn8.ent.gz S
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1nn8.ent.gz T
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1o7q.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1o7q.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ots.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ots.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p53.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p53.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p7b.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p7b.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p8j.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p8j.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p9m.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1p9m.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ppj.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ppj.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ppj.ent.gz Q
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q7s.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q7s.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1q90.ent.gz N
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qdv.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qdv.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qle.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qle.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qle.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qo1.ent.gz K
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qo1.ent.gz T
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qov.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1qov.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rer.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rer.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rh5.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rh5.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rh5.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rhz.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rhz.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rhz.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rj7.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rj7.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rvj.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rvj.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rzh.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rzh.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1rzh.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1s55.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1s55.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1s5l.ent.gz d
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1s5l.ent.gz l
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1s94.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1s94.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1scf.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1scf.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sfc.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sfc.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sfc.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sfc.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sfk.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sfk.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sl6.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sl6.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1smo.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1smo.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sqb.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1sqb.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1t3g.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1t3g.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1t92.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1t92.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1u07.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1u07.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1u19.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1u19.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1uc7.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1uc7.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1umx.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1umx.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1umx.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1urz.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1urz.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1v54.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz N
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz P
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz R
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1vf5.ent.gz T
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1wio.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1wio.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1wwa.ent.gz X
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1wwa.ent.gz Y
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1x13.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1x13.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1xe6.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1xe6.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1xfd.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1xfd.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1xhk.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1xhk.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1y1m.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1y1m.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1y2g.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1y2g.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yew.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yew.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yew.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yew.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yfo.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yfo.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ypq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ypq.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ysr.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1ysr.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yst.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yst.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1yst.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z0v.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z0v.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z8y.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z8y.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z9j.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z9j.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z9j.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z9o.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1z9o.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zcd.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zcd.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zll.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zll.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zoy.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zoy.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zrt.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zrt.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zrt.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zrt.ent.gz P
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zt4.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb1zt4.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2a06.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2a06.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2a06.ent.gz P
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2a06.ent.gz Q
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2a06.ent.gz W
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2abm.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2abm.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2aew.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2aew.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2arj.ent.gz Q
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2arj.ent.gz R
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2atp.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2atp.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2aw2.ent.gz X
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2aw2.ent.gz Y
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2axt.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2axt.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2b7k.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2b7k.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2bl2.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2bl2.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2brq.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2brq.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2bru.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2bru.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2bs2.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2bs2.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2c36.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2c36.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2c5j.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2c5j.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2cc3.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2cc3.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2dyr.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2dyr.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2dyr.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2dyr.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2e74.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2e74.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2e74.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2exy.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2exy.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2fum.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2fum.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2g3p.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2g3p.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2giq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2giq.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2goo.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2goo.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2i1y.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2i1y.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2iad.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2iad.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2j5d.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2j5d.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2j8c.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2j8c.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2j8c.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2kdc.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2kdc.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2loh.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2loh.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2lzs.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2lzs.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2m4j.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2m4j.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2mja.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2mja.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2mka.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2mka.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2mom.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2mom.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2nps.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2nps.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2nz0.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2nz0.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2oa8.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2oa8.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2oar.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2oar.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2oau.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2oau.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2occ.ent.gz N
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2occ.ent.gz P
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2occ.ent.gz W
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2p28.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2p28.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2pkd.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2pkd.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2pno.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2pno.ent.gz K
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2qto.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2qto.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2v5z.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2v5z.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2v8n.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2v8n.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2vsm.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2vsm.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wdq.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wdq.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wdq.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wgm.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wgm.ent.gz K
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wib.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wib.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wjn.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wjn.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wjn.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wwa.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wwa.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2wwa.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2xa0.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2xa0.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2xa0.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2xvt.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2xvt.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2yoa.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb2yoa.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3a0b.ent.gz a
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3a0b.ent.gz b
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3a0b.ent.gz c
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3a0b.ent.gz d
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3alq.ent.gz T
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3alq.ent.gz W
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz b
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz c
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz d
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz e
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz f
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz h
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz m
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz T
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3arc.ent.gz x
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3b5n.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3b5n.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3b5w.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3b5w.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3b60.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3b60.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bdw.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bdw.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bf0.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bf0.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bp3.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bp3.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bz1.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bz1.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bz2.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3bz2.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cdg.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cdg.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cgz.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cgz.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cio.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cio.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cwf.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cwf.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cx5.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3cx5.ent.gz N
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3dww.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3dww.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3eff.ent.gz K
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3eff.ent.gz N
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3ejj.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3ejj.ent.gz X
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3epe.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3epe.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3eu9.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3eu9.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3fru.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3fru.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3fxi.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3fxi.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3fye.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3fye.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3gxu.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3gxu.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3h6g.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3h6g.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hb3.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hb3.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hi1.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hi1.ent.gz J
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hsy.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hsy.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hup.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3hup.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3i8s.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3i8s.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3ikk.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3ikk.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3j45.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3j45.ent.gz y
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3jwd.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3jwd.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3kbh.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3kbh.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3l5j.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3l5j.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3mtr.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3mtr.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3mx0.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3mx0.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3n7s.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3n7s.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3n7s.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3npz.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3npz.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3nvq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3nvq.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3nwh.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3nwh.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3o21.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3o21.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3o8e.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3o8e.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3p4q.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3p4q.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3pgc.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3pgc.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3pk1.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3pk1.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3qd6.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3qd6.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3qd6.ent.gz U
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3qs7.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3qs7.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rgb.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rgb.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rgb.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rgb.ent.gz K
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rlf.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rlf.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rp1.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rp1.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rpk.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3rpk.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s8f.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s8f.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s8f.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s8g.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s8g.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s9d.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3s9d.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3sku.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3sku.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3sku.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3sku.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3soc.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3soc.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3tf0.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3tf0.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3u0c.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3u0c.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3ub1.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3ub1.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3v6o.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3v6o.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3vh7.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3vh7.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3vq2.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3vq2.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3wiy.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3wiy.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3wu2.ent.gz h
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3wu2.ent.gz x
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3zlc.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb3zlc.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ain.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ain.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4akz.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4akz.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4aps.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4aps.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4bjq.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4bjq.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4bog.ent.gz V
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4bog.ent.gz W
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4byh.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4byh.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4c5d.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4c5d.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4c86.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4c86.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4czb.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4czb.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ene.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ene.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4f4s.ent.gz N
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4f4s.ent.gz O
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4fvf.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4fvf.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4gjt.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4gjt.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4gt4.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4gt4.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hfi.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hfi.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hil.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hil.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hnj.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hnj.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hza.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4hza.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4i0p.ent.gz E
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4i0p.ent.gz F
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4jc6.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4jc6.ent.gz L
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4jzl.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4jzl.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4kp5.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4kp5.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4kt0.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4kt0.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ky9.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ky9.ent.gz P
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4l6v.ent.gz 1
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4l6v.ent.gz 8
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ll9.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ll9.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ms4.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ms4.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4myc.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4myc.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4n90.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4n90.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4of8.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4of8.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ofd.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ofd.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ofi.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ofi.ent.gz H
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ov5.ent.gz G
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4ov5.ent.gz M
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4p42.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4p42.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pbu.ent.gz e
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pbu.ent.gz j
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz a
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz b
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz d
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz e
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz i
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz l
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pj0.ent.gz t
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pp8.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4pp8.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4q54.ent.gz C
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4q54.ent.gz I
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4qxw.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4qxw.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4rda.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4rda.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4rwd.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4rwd.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4tph.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4tph.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4u1k.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4u1k.ent.gz D
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4u2v.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4u2v.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4v0b.ent.gz A
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4v0b.ent.gz B
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4v6m.ent.gz AZ
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4v6m.ent.gz BA
~/git/bioinfo-toolbox/parsing/extract_all_pdb_seq.py /pfs/nobackup/home/a/arnee/data/pdb/*/pdb4v6m.ent.gz BB
