#!/bin/bash
if [ ! -d /home/arnee/git/bioinfo-toolbox/arne/Corona ]
then
    mkdir -p /home/arnee/git/bioinfo-toolbox/arne/Corona
fi
cd /home/arnee/git/bioinfo-toolbox/arne/Corona
#git pull 2>/dev/null
python3 AE-analysis.py #  2>/dev/null 1>/dev/null
cd  ~/Desktop/Corona/nations/
montage -mode concatenate -tile 3x slope.png  deathslope.png  total_bar.png China_trendline.png South_Korea_trendline.png  Italy_trendline.png   Spain_trendline.png   USA_trendline.png   Sweden_trendline.png ../montage.png
cd ~/Desktop/Corona/
tree -H '.' -L 1 --noreport --charset utf-8 -T "Corona plots from Arne Elofsson"  -n  > index.html
rsync -ar -e "ssh -i ~/.ssh/id2_rsa" ~/Desktop/Corona/ ae.scilifelab.se:/var/www/html/archive.bioinfo.se/docroot/Corona/ 2>/dev/null

