#!/bin/bash
if [ ! -d /home/arnee/git/bioinfo-toolbox/arne/Corona ]
then
    mkdir -p /home/arnee/git/bioinfo-toolbox/arne/Corona
fi
cd /home/arnee/git/bioinfo-toolbox/arne/Corona
#git pull 2>/dev/null
#python3 AE-analysis.py #  2>/dev/null 1>/dev/null
python3 get_ECDC.py
python3 get_JHS.py
python3 get_JHS.py --province
python3 get_c19.py --province
python3 makeplots.py -i /home/arnee/Desktop/Corona/data/merged_ECDC.csv
python3 makeplots.py -i ~/Desktop/Corona/data/merged_province_JHS.csv -out ~/Desktop/Corona/JHS-province
python3 makeplots.py -i ~/Desktop/Corona/data/merged_JHS.csv -out ~/Desktop/Corona/JHS
python3 makeplots.py -i ~/Desktop/Corona/c19/data/merged_province_c19.csv -cutoff 10 -minconfirmed 10
cd  ~/Desktop/Corona/
#montage -mode concatenate -tile 3x slope.png  deathslope.png  total_bar.png nations/China_trendline.png nations/South_Korea_trendline.png  nations/Italy_trendline.png   nations/Spain_trendline.png   nations/USA_trendline.png   nations/Sweden_trendline.png ./montage.png
#cd ~/Desktop/Corona/
tree -H '.' -L 1 --noreport --charset utf-8 -T "Corona plots from Arne Elofsson"  -n  > index.html
for i in `find ./ -type d`
do
    pushd $i
    tree -H '.' -L 1 --noreport --charset utf-8 -T "Corona plots from Arne Elofsson"  -n  > index.html
    popd
done
rsync -ar -e "ssh -i ~/.ssh/id2_rsa" ~/Desktop/Corona/ ae.scilifelab.se:/var/www/html/archive.bioinfo.se/docroot/Corona/ 2>/dev/null

